#!/usr/bin/env python3
"""Convert camera-extracted piece keypoints into a ReassembleNet-style .pt sample.

Input is produced by the ROS-side script:
  ros2 run mirobot_gazebo_demo camera_piece_keypoint_extractor.py

Output follows the important structure generated by process_data.py:
  {
    "puzzle_name": "...",
    "0": [height, width],
    "1": [
      [[x, y], [edge_angle, curvature], local_feature],
      ...
      ["piece_name", "..."],
      ["global", global_feature],
    ],
    ...
  }

If piece crop images are present in the camera JSON, this script extracts real
ResNet-18 local/global 512D features. If not, it falls back to zero vectors.
"""

import argparse
import json
from pathlib import Path

import cv2
import numpy as np
import torch
import torch.nn as nn
import torchvision.models as models
import torchvision.transforms as transforms
from PIL import Image


def parse_args():
    parser = argparse.ArgumentParser(
        description="Convert camera_piece_keypoint_extractor JSON to ReassembleNet .pt input."
    )
    parser.add_argument("--input_json", type=Path, default=Path("/tmp/camera_piece_keypoints.json"))
    parser.add_argument("--output_pt", type=Path, default=Path("/tmp/camera_reassemblenet_sample.pt"))
    parser.add_argument("--puzzle_name", default="camera_scan_001")
    parser.add_argument("--points_per_piece", type=int, default=100)
    parser.add_argument("--texture_dim", type=int, default=512)
    parser.add_argument("--patch_size", type=int, default=32)
    parser.add_argument("--feature_batch_size", type=int, default=64)
    parser.add_argument("--normalize_piece_scale", action="store_true", help="Rescale each piece keypoint cloud to better match RePAIR training normalized piece size.")
    parser.add_argument("--target_piece_norm_size", type=float, default=0.29, help="Target normalized max(width,height) for each piece after scale normalization.")
    parser.add_argument("--feature_extractor", type=Path, default=Path("feature_extractor.pt"))
    parser.add_argument("--zero_features", action="store_true", help="Disable ResNet features and use zero vectors.")
    parser.add_argument(
        "--sort_by",
        choices=["instance_id", "x", "y", "area"],
        default="instance_id",
        help="Stable ordering for output piece keys. Use instance_id for normal extractor output.",
    )
    return parser.parse_args()


def image_size_height_width(payload):
    # camera_piece_keypoint_extractor stores [width, height].
    width, height = payload.get("image_size", [640, 480])
    return [int(height), int(width)]


def sorted_pieces(pieces, sort_by):
    if sort_by == "x":
        return sorted(pieces, key=lambda item: (item.get("center_pixel", [0, 0])[0], item.get("center_pixel", [0, 0])[1]))
    if sort_by == "y":
        return sorted(pieces, key=lambda item: (item.get("center_pixel", [0, 0])[1], item.get("center_pixel", [0, 0])[0]))
    if sort_by == "area":
        return sorted(pieces, key=lambda item: float(item.get("area", 0.0)), reverse=True)
    return sorted(pieces, key=lambda item: int(item.get("instance_id", 0)))


def point_rows_from_piece(piece):
    rows = []
    for row in piece.get("keypoints", []):
        pixel = row.get("pixel")
        if not isinstance(pixel, list) or len(pixel) != 2:
            continue
        rows.append([
            [int(round(pixel[0])), int(round(pixel[1]))],
            [float(row.get("edge_angle_deg", 0.0)), float(row.get("curvature", 0.0))],
        ])

    if rows:
        return rows

    # Fallback: use raw contour points with zero geometry if Harris keypoints are unavailable.
    for pixel in piece.get("contour", []):
        if isinstance(pixel, list) and len(pixel) == 2:
            rows.append([
                [int(round(pixel[0])), int(round(pixel[1]))],
                [0.0, 0.0],
            ])
    return rows


def pad_or_trim(rows, target_count):
    if not rows:
        return []
    result = list(rows[:target_count])
    while len(result) < target_count:
        result.append(result[-1])
    return result


def normalize_piece_scale_rows(rows, image_size_hw, target_norm_size):
    if not rows:
        return rows, 1.0
    height, width = float(image_size_hw[0]), float(image_size_hw[1])
    points = np.array([row[0] for row in rows], dtype=np.float64)
    center = points.mean(axis=0)
    current_norm_w = (points[:, 0].max() - points[:, 0].min()) / max(height, 1.0)
    current_norm_h = (points[:, 1].max() - points[:, 1].min()) / max(width, 1.0)
    current = max(current_norm_w, current_norm_h, 1e-9)
    scale = float(target_norm_size / current)

    scaled_points = center + (points - center) * scale
    scaled_points[:, 0] = np.clip(scaled_points[:, 0], 0, max(height - 1.0, 0.0))
    scaled_points[:, 1] = np.clip(scaled_points[:, 1], 0, max(width - 1.0, 0.0))

    normalized = []
    for row, point in zip(rows, scaled_points):
        normalized.append([
            [int(round(point[0])), int(round(point[1]))],
            row[1],
        ])
    return normalized, scale


class ResNetFeatureExtractor:
    def __init__(self, weights_path):
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        model = models.resnet18()
        model = nn.Sequential(*list(model.children())[:-1])
        if weights_path and weights_path.exists():
            print(f"loading feature extractor weights: {weights_path}")
            model.load_state_dict(torch.load(weights_path, map_location=self.device, weights_only=False))
        else:
            print(f"feature extractor weights not found: {weights_path}; using torchvision ResNet-18 initialization")
        self.model = model.to(self.device).eval()
        self.transform = transforms.Compose([
            transforms.Resize((224, 224)),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
        ])

    def extract(self, pil_image):
        return self.extract_many([pil_image], batch_size=1)[0]

    def extract_many(self, pil_images, batch_size=64):
        features = []
        for start in range(0, len(pil_images), batch_size):
            chunk = pil_images[start:start + batch_size]
            tensors = []
            for image in chunk:
                if image.mode == "RGBA":
                    image = image.convert("RGB")
                tensors.append(self.transform(image))
            batch = torch.stack(tensors, dim=0).to(self.device)
            with torch.inference_mode():
                feat = self.model(batch)
            features.extend(feat.squeeze(-1).squeeze(-1).detach().cpu().tolist())
        return features


def load_piece_crop(piece):
    crop_path = piece.get("images", {}).get("crop")
    if not crop_path:
        return None, None
    path = Path(crop_path)
    if not path.exists():
        return None, None
    image_bgr = cv2.imread(str(path), cv2.IMREAD_COLOR)
    if image_bgr is None:
        return None, None
    image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)
    return image_rgb, path


def crop_local_patch(image_rgb, keypoint_full_pixel, bbox, patch_size):
    x0, y0, _, _ = bbox
    x = int(round(keypoint_full_pixel[0] - x0))
    y = int(round(keypoint_full_pixel[1] - y0))
    half = patch_size // 2
    x1 = max(x - half, 0)
    y1 = max(y - half, 0)
    x2 = min(x + half + 1, image_rgb.shape[1])
    y2 = min(y + half + 1, image_rgb.shape[0])
    patch = image_rgb[y1:y2, x1:x2]

    bottom_pad = max(0, patch_size - patch.shape[0])
    right_pad = max(0, patch_size - patch.shape[1])
    if bottom_pad > 0 or right_pad > 0:
        patch = cv2.copyMakeBorder(
            patch,
            0,
            bottom_pad,
            0,
            right_pad,
            borderType=cv2.BORDER_CONSTANT,
            value=(255, 255, 255),
        )
    return Image.fromarray(patch).convert("RGB")


def main():
    args = parse_args()
    with args.input_json.open("r", encoding="utf-8") as f:
        payload = json.load(f)

    pieces = sorted_pieces(payload.get("pieces", []), args.sort_by)
    if not pieces:
        raise ValueError(f"no pieces found in {args.input_json}")

    zero_texture = [0.0] * args.texture_dim
    extractor = None if args.zero_features else ResNetFeatureExtractor(args.feature_extractor)
    image_size_hw = image_size_height_width(payload)
    sample = {
        "puzzle_name": args.puzzle_name,
        "0": image_size_hw,
    }

    feature_mode_by_piece = {}
    scale_mode_by_piece = {}
    for output_index, piece in enumerate(pieces, start=1):
        point_rows = pad_or_trim(point_rows_from_piece(piece), args.points_per_piece)
        if not point_rows:
            raise ValueError(f"piece instance_id={piece.get('instance_id')} has no keypoints or contour points")

        scale_factor = 1.0
        if args.normalize_piece_scale:
            point_rows, scale_factor = normalize_piece_scale_rows(point_rows, image_size_hw, args.target_piece_norm_size)

        crop_rgb, crop_path = load_piece_crop(piece)
        bbox = piece.get("bbox")
        use_real_features = extractor is not None and crop_rgb is not None and isinstance(bbox, list) and len(bbox) == 4

        if use_real_features:
            global_feature = extractor.extract(Image.fromarray(crop_rgb).convert("RGB"))
            patches = [crop_local_patch(crop_rgb, point, bbox, args.patch_size) for point, _ in point_rows]
            local_features = extractor.extract_many(patches, batch_size=args.feature_batch_size)
            feature_mode = "resnet18_crop_local_global"
        else:
            global_feature = zero_texture
            local_features = [zero_texture] * len(point_rows)
            feature_mode = "zero_feature_fallback"

        payload_rows = []
        for (point, geometry), local_feature in zip(point_rows, local_features):
            payload_rows.append([point, geometry, local_feature])

        instance_id = piece.get("instance_id", output_index)
        payload_rows.append(["piece_name", f"camera_piece_{instance_id}"])
        payload_rows.append(["global", global_feature])
        sample[str(output_index)] = payload_rows
        feature_mode_by_piece[str(output_index)] = {
            "mode": feature_mode,
            "crop": str(crop_path) if crop_path else None,
        }
        scale_mode_by_piece[str(output_index)] = {
            "normalize_piece_scale": bool(args.normalize_piece_scale),
            "target_piece_norm_size": args.target_piece_norm_size,
            "applied_scale_factor": scale_factor,
        }

    sample["camera_adapter_meta"] = {
        "input_json": str(args.input_json),
        "feature_extractor": str(args.feature_extractor),
        "zero_features": bool(args.zero_features),
        "patch_size": args.patch_size,
        "feature_batch_size": args.feature_batch_size,
        "normalize_piece_scale": bool(args.normalize_piece_scale),
        "target_piece_norm_size": args.target_piece_norm_size,
        "feature_mode_by_piece": feature_mode_by_piece,
        "scale_mode_by_piece": scale_mode_by_piece,
    }

    args.output_pt.parent.mkdir(parents=True, exist_ok=True)
    torch.save(sample, args.output_pt)

    print(f"wrote {args.output_pt}")
    print(f"input_json: {args.input_json}")
    print(f"puzzle_name: {sample['puzzle_name']}")
    print(f"image_size_height_width: {sample['0']}")
    print(f"pieces: {len(pieces)}")
    for output_index in range(1, len(pieces) + 1):
        rows = sample[str(output_index)]
        mode = feature_mode_by_piece[str(output_index)]["mode"]
        scale = scale_mode_by_piece[str(output_index)]["applied_scale_factor"]
        print(f"piece_{output_index}: point_rows={len(rows) - 2} piece_name={rows[-2][1]} feature_mode={mode} scale_factor={scale:.3f}")


if __name__ == "__main__":
    main()
